name: Devcontainer Image CI

on:
  push:
    branches: ["main"]

jobs:
  build-push-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Install dev-container-cli
        run: npm install -g "@vscode/dev-container-cli"

      - name: Build dev container
        run: devcontainer build --image-name ${{ secrets.REGISTRY_URL }}/dotnet-devcontainer --workspace-folder .

      - name: Push dev container to Azure Container Registry
        run: docker push ${{ secrets.REGISTRY_URL }}/dotnet-devcontainer
