name: Devcontainer Image CI

on:
  push:
    branches: ["main"]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build  -t ${{ secrets.REGISTRY_URL }}/dotnet-dev-container:${{ github.sha }} ../../.devcontainer
          docker push ${{ secrets.REGISTRY_URL }}/dotnet-dev-container:${{ github.sha }}
