name: Devcontainer Image CI

on:
  push:
    branches: ["main"]
    paths:
      - ".devcontainer/**/*"
      - ".github/**/*"

jobs:
  build-push-dev-container:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.REGISTRY_URL }}/dotnet-devcontainer
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Install dev container CLI
        run: npm install -g "@vscode/dev-container-cli"

      - name: Build dev container
        run: devcontainer build --no-cache --image-name ${{ env.IMAGE_NAME }} --workspace-folder .

      - name: Push dev container to Azure Container Registry
        run: docker push ${{ env.IMAGE_NAME }}
